# Generated by Django 3.2.8 on 2021-10-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='desc_link',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='desc_servciec_include',
        ),
    ]
